import type { GlobalThemeOverrides } from 'naive-ui'

export const notionThemeOverrides: GlobalThemeOverrides = {
  common: {
    primaryColor: '#0075de',
    primaryColorHover: '#2d8ae3',
    primaryColorPressed: '#005bab',
    primaryColorSuppl: '#0075de',
    infoColor: '#62aef0',
    successColor: '#1aae39',
    warningColor: '#dd5b00',
    errorColor: '#e54d2e',
    textColorBase: '#000000',
    textColor1: '#000000',
    textColor2: '#31302e',
    textColor3: '#615d59',
    
    fontSize: '16px',
    fontSizeMini: '12px',
    fontSizeSmall: '14px',
    fontSizeMedium: '15px',
    fontSizeLarge: '16px',
    fontSizeHuge: '22px',
    fontFamily: 'v-sans, Inter, -apple-system, system-ui, "Segoe UI", Helvetica, Arial, sans-serif',
    fontFamilyMono: 'v-mono, "Fira Code", "SF Mono", ui-monospace, Menlo, Monaco, Consolas, monospace',
    borderRadius: '5px',
    borderRadiusSmall: '4px',
    
    
    dividerColor: '#e6e6e6',
    borderColor: '#e6e6e6',
    hoverColor: '#f6f5f4',
    bodyColor: '#f6f5f4',
    cardColor: '#ffffff',
    modalColor: '#ffffff',
    popoverColor: '#ffffff',
    tableColor: '#ffffff',
    inputColor: '#ffffff',
    actionColor: '#f6f5f4',
    heightTiny: '28px',
    heightSmall: '34px',
    heightMedium: '40px',
    heightLarge: '48px',
    heightHuge: '56px',
  },
  Button: {
    borderRadiusSmall: '8px',
    borderRadiusMedium: '9999px',
    borderRadiusLarge: '9999px',
    fontSizeTiny: '12px',
    fontSizeSmall: '14px',
    fontSizeMedium: '16px',
    fontSizeLarge: '16px',
    fontWeight: '500',
    heightTiny: '28px',
    heightSmall: '34px',
    heightMedium: '40px',
    heightLarge: '48px',
    paddingTiny: '0 14px',
    paddingSmall: '0 18px',
    paddingMedium: '0 24px',
    paddingLarge: '0 28px',
    colorPrimary: '#0075de',
    colorHoverPrimary: '#2d8ae3',
    colorPressedPrimary: '#005bab',
    colorFocusPrimary: '#2d8ae3',
    colorSecondary: '#ffffff',
    colorHoverSecondary: '#f6f5f4',
    colorPressedSecondary: '#e6e6e6',
    textColorPrimary: '#ffffff',
    textColorHoverPrimary: '#ffffff',
    textColorPressedPrimary: '#ffffff',
    textColorSecondary: '#000000',
    textColorHoverSecondary: '#000000',
    textColorPressedSecondary: '#31302e',
    borderSecondary: '1px solid #e6e6e6',
    borderHoverSecondary: '1px solid #e6e6e6',
    borderPressedSecondary: '1px solid #d0d0d0',
  },
  Card: {
    borderRadius: '12px',
    fontSize: '15px',
    paddingSmall: '16px',
    paddingMedium: '24px',
    paddingLarge: '24px',
    paddingHuge: '32px',
    color: '#ffffff',
    borderColor: '#e6e6e6',
    titleFontSizeSmall: '15px',
    titleFontSizeMedium: '16px',
    titleFontSizeLarge: '20px',
    titleFontSizeHuge: '22px',
    titleFontWeight: '600',
  },
  Input: {
    borderRadius: '4px',
    fontSize: '15px',
    heightSmall: '34px',
    heightMedium: '40px',
    heightLarge: '48px',
    paddingSmall: '6px 8px',
    paddingMedium: '6px 10px',
    paddingLarge: '6px 12px',
    color: '#ffffff',
    colorFocus: '#ffffff',
    border: '1px solid #e6e6e6',
    borderHover: '1px solid #d0d0d0',
    borderFocus: '1px solid #0075de',
    boxShadowFocus: '0 0 0 2px rgba(0, 117, 222, 0.15)',
    caretColor: '#0075de',
    // #8a847e on white = 4.5:1 contrast (WCAG AA for normal text)
    placeholderColor: '#8a847e',
  },
  DataTable: {
    borderColor: '#e6e6e6',
    thColor: '#f6f5f4',
    thTextColor: '#615d59',
    thFontWeight: '600',
    thFontSize: '12px',
    tdColor: '#ffffff',
    tdTextColor: '#000000',
    tdFontSize: '15px',
    borderRadius: '12px',
  },
  Tag: {
    borderRadius: '9999px',
    fontSize: '12px',
    heightSmall: '22px',
    heightMedium: '26px',
    heightLarge: '30px',
  },
  Menu: {
    borderRadius: '5px',
    itemTextColor: '#31302e',
    itemTextColorHover: '#000000',
    itemTextColorActive: '#0075de',
    itemTextColorChildActive: '#0075de',
    itemColorActive: 'rgba(0, 117, 222, 0.06)',
    itemColorHover: '#f6f5f4',
    itemIconColor: '#615d59',
    itemIconColorHover: '#31302e',
    itemIconColorActive: '#0075de',
    fontSize: '15px',
    itemHeight: '44px',
  },
  Form: {
    labelFontSize: '15px',
    labelTextColor: '#31302e',
    feedbackFontSize: '12px',
    feedbackTextColorError: '#e54d2e',
    feedbackTextColorWarning: '#dd5b00',
  },
  Alert: {
    borderRadius: '8px',
    fontSize: '15px',
  },
  Tabs: {
    tabTextColorLine: '#615d59',
    tabTextColorActiveLine: '#0075de',
    tabTextColorHoverLine: '#31302e',
    barColor: '#0075de',
    tabGapMediumLine: '24px',
    tabGapLargeLine: '32px',
  },
  Modal: {
    borderRadius: '16px',
    color: '#ffffff',
  },
  Descriptions: {
    borderRadius: '8px',
    thColor: '#f6f5f4',
    thTextColor: '#615d59',
    thFontWeight: '600',
    tdColor: '#ffffff',
    tdTextColor: '#000000',
    fontSize: '15px',
  },
  Steps: {
    textColorProcess: '#0075de',
    textColorFinish: '#1aae39',
    textColorWait: '#a39e98',
    indicatorColorProcess: '#0075de',
    indicatorColorFinish: '#1aae39',
    indicatorColorWait: '#e6e6e6',
  },
  Select: {
    borderRadius: '4px',
    peers: {
      InternalSelection: {
        borderRadius: '4px',
        fontSizeMedium: '15px',
        heightMedium: '40px',
        border: '1px solid #e6e6e6',
        borderHover: '1px solid #d0d0d0',
        borderFocus: '1px solid #0075de',
        boxShadowFocus: '0 0 0 2px rgba(0, 117, 222, 0.15)',
        textColor: '#000000',
        placeholderColor: '#8a847e',
      },
    },
  },
  Switch: {
    railColorActive: '#0075de',
  },
  Statistic: {
    fontSize: '22px',
    fontWeight: '700',
    labelFontSize: '12px',
    labelTextColor: '#615d59',
    valueTextColor: '#000000',
  },
  Code: {
    borderRadius: '8px',
    fontSize: '14px',
  },
  Space: {
    gapSmall: '8px',
    gapMedium: '12px',
    gapLarge: '16px',
  },
  Layout: {
    siderColor: '#f6f5f4',
    siderBorderColor: '#e6e6e6',
    headerColor: '#ffffff',
    headerBorderColor: '#e6e6e6',
    contentColor: '#f6f5f4',
  },
}